Enhance SAM deployment process with error handling and output logging; add .dockerignore to exclude unnecessary files

diff --git a/.github/workflows/deploy-infra.yml b/.github/workflows/deploy-infra.yml
--- a/.github/workflows/deploy-infra.yml
+++ b/.github/workflows/deploy-infra.yml
@@ -99,12 +99,28 @@ jobs:
 
       # Deploy with SAM
       - name: SAM Deploy
+        id: sam_deploy
         run: |
-          sam deploy \
+          set -o pipefail # Ensures that a pipeline returns the exit status of the last command that failed.
+
+          output=$(sam deploy \
             --parameter-overrides \
               "SharedApiId=${{ steps.get_exports.outputs.shared_api_id }}" \
               "EEGUploadBucketName=${{ steps.get_exports.outputs.bucket_name }}" \
               "PrivateSG=${{ steps.get_exports.outputs.sg_id }}" \
               "PrivateSubnetId1=${{ steps.get_exports.outputs.subnet1_id }}" \
               "PrivateSubnetId2=${{ steps.get_exports.outputs.subnet2_id }}" \
-            --no-confirm-changeset
+            --no-confirm-changeset 2>&1) # Redirect stderr to stdout
+
+          exit_code=$?
+          echo "$output" # Print the output so it's visible in the logs
+
+          if [ $exit_code -ne 0 ]; then
+            if echo "$output" | grep -q "No changes to deploy. Stack ${STACK_NAME} is up to date"; then
+              echo "::notice::SAM deploy reported no changes, considering it a success."
+              exit 0 # Exit with success code
+            else
+              echo "::error::SAM deploy failed with an unexpected error."
+              exit $exit_code # Re-exit with the original error code for actual failures
+            fi
+          fi
